fun main() {
    //   Classes,Abstract Classes,Inheritance
    /*val developer = Developer("Snowden",Sex.Male,2,"kotlin")
     developer.getDetails()
     val pizza = Pizza("peperoni")
     pizza.getDetails()
     val beer = Beer("Bud")
     beer.getDetails()
     developer.eat(pizza)
     developer.eat(beer)
     developer.code()
     developer.die()*/

    //Interfaces
    val sonyTV = TVImpl("Sony", "Bravia")
    sonyTV.getDetails()
    println("")
    sonyTV.adjustChannel("MTV")
    println("")
    println("Content: " + sonyTV.turnOn()?.content)
    println("")
    println("Content: " + sonyTV.adjustChannel("MTV")?.content)
    println("")
    println("Content: " + sonyTV.adjustChannel("Discovery")?.content)
    println("")
    sonyTV.getDetails()
    println("")
    println("Content: " + sonyTV.switchChannel(10)?.content)
    println("")
    println("Content: " + sonyTV.switchChannel(0)?.content)
    println("")
    sonyTV.turnOff()
    println("")
    println("Content: " + sonyTV.turnOn()?.content)
    println("")
    println("Content: " + sonyTV.turnOn()?.content)
    println("")
    sonyTV.turnOff()
    println("")
    println("Content: " + sonyTV.displayInputStream(null))
}